# Site settings
title: Simon Xu
email: simon.shoo@gmail.com
url: https://example.github.io
description: "Website fully dedicated to me, Simon Xu, on his journey to finding his engineering dream job."
skills: "Mechanical/Electrical Engineer - Application Developer - CAD Modeler"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Simon Xu
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, bitbucket, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/simonjxu
  - title: github
    url: http://github.com/simjxu	
  - title: youtube
    url: https://www.youtube.com/channel/UCjARdYahvCdeoJDpPCPpqaw
  - title: twitter
    url: http://twitter.com/SimonXu_
  - title: facebook
    url: https://www.facebook.com/simonjxu

# Postal address (add as many lines as necessary)
address:
  - line: San Francisco, CA 94107
  - line: SOMA district

# Credits content
credits: 'I am using an open source Bootstrap theme made by <a href="http://startbootstrap.com">Start Bootstrap</a>. Also, special thanks to Github pages, where I am hosting this webpage for free!'

# Build settings
markdown: kramdown
permalink: pretty
